### PR TITLE
Added os.environ

### PR DESCRIPTION
**Pull request by Kenneth-G**
Hi, I am looking for projects to contribute to as part of Hacktoberfest. 
From looking at issue #1 I saw you were looking to change your program to use os.environ. I've made the change. I hope I was able to help. This is my first Hacktoberfest so please let me know if I made any mistakes. 

Thank you.

### CODE REVIEW

**Comment by HallBregg** [comment]
Thanks for joining to my little project. I need some time to review your code, but feel free to solve next issue from my list ;)

**Comment by Kenneth-G** [comment]
Ha for sure! Could you give me more of an idea for what this project is about? :)

**Comment by HallBregg** [comment]
The main idea is to download data from https://justjoin.it/ and save it to the PostgreSQL DB.
Afterwards I would like to build some statistics from that data :)

**Comment by Kenneth-G** [comment]
I'll try to help out for sure. I'm still learning to code and would love to contribute to more open source projects.

**Pull request merged**
